controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_produit_showAdmin:
    path: '/Admin'
    controller: 'App\Controller\ProduitController::indexAdmin'




app_produit_panier:
    path: /panier
    controller: 'App\Controller\PanierController::ajouterAuPanier'
    methods: ['POST']









